In [3]:
import time

In [6]:
a = list(range(1000000))
b = list(range(1000000))

start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]
end_p = time.perf_counter()
total_p = end_p - start_p
print("Python:", total_p)

Python: 0.06938950000039767


In [4]:
import numpy as np

In [7]:
a_np = np.array(a)
b_np = np.array(b)

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n = end_n - start_n
print("NumPy:", total_n)

NumPy: 0.02119230000243988


In [8]:
print(f"Numpy is faster than python by : {total_p/total_n:.2f}")

Numpy is faster than python by : 3.27


# creating arrays in numpy

### 1. np.array()

In [9]:
arr_1 = np.array([1,2,3])

print(arr_1)
print(type(arr_1))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2)
print(type(arr_2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
arr_2[0]

array([1, 2, 3])

In [12]:
arr_2[0][1]

np.int64(2)

In [13]:
arr_3 = np.array([1,2,3, "hello"])

print(arr_3)
print(type(arr_3))

['1' '2' '3' 'hello']
<class 'numpy.ndarray'>


In [14]:
print(type(arr_3[0]))

<class 'numpy.str_'>


In [15]:
print(type(arr_3[1]))

<class 'numpy.str_'>


In [17]:
arr_4 = np.array([1,2,3], dtype=np.int8)  #here dtype we can change type of array
print(type(arr_4))

<class 'numpy.ndarray'>


In [18]:
type(arr_4[0])

numpy.int8

In [19]:
print(type(arr_4))

<class 'numpy.ndarray'>


In [20]:
arr_5 = np.array([1,2,3, "hello"], dtype=np.float16)

ValueError: could not convert string to float: 'hello'

In [21]:
arr_6 = np.array([1,2,3, "10"], dtype=np.float16)

In [22]:
arr_6

array([ 1.,  2.,  3., 10.], dtype=float16)

In [23]:
print(arr_6[3]) #precision means numbers after decimal

10.0


## 2. np.arange(start,stop,step)

In [24]:
list(range(1,20,2)) #normal range() in python

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [25]:
print(np.arange(1,20,2)) # arange() in numpy

[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
a=np.array(np.arange(1,11,2)) ## np.arange gives 1D

In [27]:
a

array([1, 3, 5, 7, 9])

In [28]:
b=np.arange(1,11,2)

In [29]:
print(type(b))

<class 'numpy.ndarray'>


In [30]:
b

array([1, 3, 5, 7, 9])

## np.linspace(start,stop, num=x)
## stop - inclusive

In [31]:
np_linespc=np.linspace(1,100,5)

In [33]:
np_linespc

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [35]:
print(type(np_linespc))

<class 'numpy.ndarray'>


In [34]:
np_linespc_1=np.linspace(1,10,10)
print(np_linespc_1)
print(type(np_linespc_1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [35]:
for num in np.linspace(1,10,10):
    print(num)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
for num in np.linspace(1,10,10, dtype=np.int8):  #by default it is float, we can convert to int by using dtype
    print(num)

1
2
3
4
5
6
7
8
9
10


## 4. np.zeros(shape)
# shape of matrix

In [36]:
npz_1= np.zeros(5)

In [37]:
npz_1

array([0., 0., 0., 0., 0.])

In [38]:
print(type(npz_1))

<class 'numpy.ndarray'>


In [39]:
npz_2= np.zeros((5,5))

In [40]:
npz_2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
npz_3= np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [55]:
npz_3.ndim #ndim tells how many dimesions

3

## 5. np.ones(shape)
# shape of matrix

In [56]:
npo_1=np.ones((2,3))
print(npo_1)

[[1. 1. 1.]
 [1. 1. 1.]]


## 6. np.full(shape,fill)

In [42]:
npf_1=np.full((2,3),10)
print(npf_1)

[[10 10 10]
 [10 10 10]]


In [51]:
npf_2=np.full((3,3),5)
print(npf_2)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


## 7. np.eye(shape)
## does not exist in 1D
# min of 2D shape


In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## 8. np.empty(shape)

In [45]:
np.empty((2,2))

array([[0.0000000e+000, 1.5092582e-311],
       [1.5092582e-311, 1.5092582e-311]])

In [46]:
np.empty((2,2), dtype=np.int8)

array([[0, 1],
       [1, 1]], dtype=int8)

In [64]:
np.empty((2,2), dtype=np.float16)

array([[0.   , 0.   ],
       [0.   , 1.984]], dtype=float16)

In [47]:
start_e = time.perf_counter()
np.empty((5,5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

7.6299998909235e-05


In [48]:
start_we = time.perf_counter()
np.ones((5,5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

0.00014010000450070947


### 9. np.random.rand(shape)

random values between 0 and 1

- ML weights random initialization

In [50]:
# 1Dim array  --> Vector
# 2 Dimen array --> matrix
print(np.random.rand(2,8))  #it support matrices only  gives 2D , 1D as per given 

[[0.97133436 0.64035597 0.90056269 0.63546053 0.25728534 0.02054801
  0.44529542 0.03274026]
 [0.35775947 0.70956516 0.04706433 0.57083683 0.42721533 0.62040967
  0.79311774 0.02376249]]


# Numpy Array attributes

### 1. ndarray.shape - it gives the shape of give array

In [52]:
arr_s= np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr_s)
print(arr_s.shape)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
(3, 3)


## 2. ndarray.ndim - it gives the dimension of the array

In [ ]:
print(arr_s.ndim)  # 2 Dimension array for above

2


### 3. ndarray.size - it returns the total no. of elements  in the array

In [54]:
print(arr_s.size)

9


## 4. ndarray.dtype - tells the datatype of array elements

In [55]:
print(arr_s.dtype)

int64


## 5.ndarray.itemsize - returns the size in bytes of one element

1 byte - 8 bits
int8 - 8 bits
int64 - int8 * 8 --> int64

In [56]:
print(arr_s.itemsize)

8


### 6. ndarray.nbytes - total number of bytes consumed by the array

In [58]:
arr_s= np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr_s)
print(arr_s.nbytes) # total 9 elements , 9 * 8 --> 72

[[1 2 3]
 [3 4 5]
 [5 6 7]]
72


### 7. ndarray.T - Returns the transpose of the array.

In [61]:
arr_s= np.array([[1,2,3],[3,4,5]]) ## now it is 2 rows, 3columns, so T will transpose to 3 rows, 2colums
print(arr_s.T)

[[1 3]
 [2 4]
 [3 5]]


# Array Reshaping and resizing in Numpy**

### 1. reshape() - change shape without changing data.
  - The total no. of elements must remain the same.
  - reshape() returns a new view if possible (no copy).
  - you can use -1 to let Numpy infer one dimension.

In [63]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)


In [64]:
# 2*3
# 3*2
# 6*1
# 4*2 - Not possible

In [65]:
reshaped_1 = arr.reshape(2,3)
print(reshaped_1)

[[1 2 3]
 [4 5 6]]


In [66]:
reshaped_1 = arr.reshape(3,2)
print(reshaped_1)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
reshaped_2 = arr.reshape(6,1)
print(reshaped_2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [69]:
reshaped_3 = arr.reshape(1,6)
print(reshaped_3)
print(reshaped_3.ndim)

[[1 2 3 4 5 6]]
2


In [ ]:
arr_3 = np.array([1,2,3,4,5,6,34,55,77,33,56,77])
reshape4= arr_3.reshape(3,-1)  # here -1 means the reshape will auto decide the 2nd size by no of elements given in araay.
print(reshape4)
print(reshape4.shape)
print(reshape4.ndim)


[[ 1  2  3  4]
 [ 5  6 34 55]
 [77 33 56 77]]
(3, 4)
2


## 2. ravel()
 -  Flatten into 1D(returns a view)
 - Fast and memory efficient
 - Changes reflect in the original array(if no copy made)

In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[3,4,5]])

In [3]:
a.shape

(2, 2)

In [5]:
print(a.ravel())

[1 2 3 4]


In [6]:
a

array([[1, 2],
       [3, 4]])

In [8]:
a_ravel=a.ravel()
print(a_ravel)
print(id(a))
print(id(a_ravel))
print(id(a.ravel()))


[1 2 3 3 4 5]
2399798323568
2399798323664
2399798322512


## .__array_interface_['data'][0]

### - the above attribute gives you the actual memory address where the raw array data begins

In [9]:
print(f"Data address of 'a' : {a.__array_interface__['data'][0]}")

Data address of 'a' : 2399500027616


In [10]:
print(f"Data address of a.ravel() directly : {a.ravel().__array_interface__['data'][0]}")

Data address of a.ravel() directly : 2399500027616


In [11]:
print(f"Data address of a_ravel) directly : {a_ravel.__array_interface__['data'][0]}")

Data address of a_ravel) directly : 2399500027616


In [12]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [13]:
a[0][0]

np.int64(1)

In [ ]:
a[0][0]=11  ## changed the element in array , but address of a does not changed

In [15]:
a

array([[11,  2,  3],
       [ 3,  4,  5]])

In [16]:
print(f"Data address of 'a' : {a.__array_interface__['data'][0]}")

Data address of 'a' : 2399500027616


## 3. flatten() - Flatten into 1D(returns a copy - new memory location)

In [17]:
a

array([[11,  2,  3],
       [ 3,  4,  5]])

In [18]:
b=a.flatten()

In [19]:
b

array([11,  2,  3,  3,  4,  5])

In [ ]:
print(f"Data address of 'a' : {a.__array_interface__['data'][0]}")
print(f"Data address of 'b' : {b.__array_interface__['data'][0]}") ## new copy as we can see diff address

Data address of 'a' : 2399500027616
Data address of 'b' : 2399462652368


## 4.resize()
 - resize array in-place
 - unlike reshape(), it can change total size. Data may be truncated or padded with zeros.

In [27]:
a=np.array([[1,2,3],[4,5,6]])

In [22]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [25]:
a.resize((3,3), refcheck=False)

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [35]:
a.resize((3,3), refcheck=False)

In [36]:
print(a)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [ ]:
a.resize((2,2), refcheck=False) ##In-place : means changing the data without reassignment

In [38]:
a

array([[1, 2],
       [3, 4]])

## 5.squeeze()
 - Remove single dimension axes
 - Useful for removing extra dimensions from image or model output shapes like (1,28,28,1)

In [40]:
a=np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [41]:
b=np.squeeze(a)

In [42]:
b

array([1, 2, 3])

In [43]:
b.ndim

1

In [44]:
b.shape

(3,)

### Indexing and Slicing in Numpy --> Beginner to Advanced

In [ ]:
## Slicing syntax : array[start:stop:step]

In [45]:
arr = np.array([10,20,30,40,50,60,70,90])

In [46]:
print(arr[0],arr[6])

10 70


In [ ]:
#arr = np.array([10,20,30,40,50,60,70,90])
#array[start:stop:step]

print(arr[1:5])
print(arr[::2])
print(arr[::-1]) #reversing the array


[20 30 40 50]
[10 30 50 70]
[90 70 60 50 40 30 20 10]


In [50]:
print(arr[:3])

[10 20 30]


## 2. Indexing in 2D arrays

In [53]:
mat = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
# i want to acess element 2
mat[0][2] #or mat[0,1] as it is matrix,it allow like this

np.int64(3)

In [ ]:
mat[0,1] #this will be fast compared to above

np.int64(2)

In [58]:
# i want to get elements 3,6,9 so  i need all rows and 2nd element of all rows
mat = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
mat[:,2]

array([3, 6, 9])

In [60]:
# i need 2,3,5,6 elements
 # [
   #     [1,2,3],
  #      [4,5,6],
 #       [7,8,9]
#    ]
mat[0:2,1:]

array([[2, 3],
       [5, 6]])

In [61]:
## to reverse entire rows & columns of matrix
mat[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

## 3.Boolean Indexing

In [64]:
arr=np.array([5,10,15,20,25,30])

In [ ]:
# i want to get all elements > 15
l=[]
for i in arr:
    if i>15:
        l.append(i)

l=np.array(l)
print(l)

#or
# arr[arr>15]

[20 25 30]


In [68]:
nw_arr = arr[arr>15]
print(nw_arr)

[20 25 30]


## 4. Fancy Indexing

In [69]:
arr = np.array([100,200,300,400,500,600])

In [70]:
indices=[0,2,4]
arr[indices]

array([100, 300, 500])

In [71]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
mat[(1,2),(0,0)]

array([4, 7])

## 5. Modifying with Indexing

In [ ]:
arr=np.array([1,2,3,4,5])
arr[2]=10  #modifying the 2nd position
print(arr)

[ 1  2 10  4  5]


In [76]:
arr[arr>2]=100
print(arr)

[  1   2 100 100 100]


## 6. Indexing with np.where()

In [77]:
arr = np.array([10,15,20,50,60,70])

In [78]:
idx=np.where(arr>20)

In [79]:
print(idx)

(array([3, 4, 5]),)


In [80]:
print(arr[idx])

[50 60 70]


### Element wise calculations

In [1]:
import numpy as np

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])


In [ ]:
print(a+b) ## addition in numpy , faster than normal python calculations
print(a*b) #Element wise multiplication 

In [ ]:
## we also have . product

np.dot(a,b) ## .dot product means multiplication and then addition(summation)

np.int64(32)

In [8]:
print(np.dot(a,b))

32


In [9]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8,9],[10,11,12]])

In [14]:
print(a1.shape)
print(a2.shape)

(2, 3)
(2, 3)


In [11]:
np.dot(a1,a2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [15]:
np.dot(a1,a2.T)

array([[ 50,  68],
       [122, 167]])

In [16]:
print((a2.T).shape)

(3, 2)


In [17]:
# apple, banana, smartphone, toy, furniture
shop_sold_amazon = np.array([
    [100, 200, 20, 30, 5], # state-1-product-sold
    [200, 400, 40, 60, 10] # state-2-product-sold
])
print(shop_sold_amazon.shape)

(2, 5)


In [18]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220] # state-2-price
])
print(price_amazon.shape)

(2, 5)


In [19]:
price_amazon.T

array([[  30,   34],
       [  10,   12],
       [1000, 1100],
       [  10,   11],
       [ 200,  220]])

In [20]:
sales = np.dot(shop_sold_amazon, price_amazon.T)

In [21]:
sales

# [[state_1(price_of_state_1), state_1(price_of_state_2)]
# [state_2(price_of_state_1), state_2(price_of_state_2)]]

array([[26300, 29230],
       [52600, 58460]])

In [22]:
diag = np.eye(2)
print(diag)

[[1. 0.]
 [0. 1.]]


In [23]:
np.sum(sales*diag)

np.float64(84760.0)

# Aggregation function

In [24]:
a_2 = np.array([1,2,3,4,5])

In [ ]:
print(np.sum(a_2)) #sum() 

15


In [27]:
np.max(a_2)

np.int64(5)

In [28]:
np.min(a_2)

np.int64(1)

In [29]:
np.argmax(a_2)

np.int64(4)

In [30]:
a3=[3,5,450,10,20,600,30,3]
np.argmax(a3)

np.int64(5)

In [31]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220] # state-2-price
])

In [32]:
np.sum(price_amazon)

np.int64(2627)

In [33]:
np.argmax(price_amazon)

np.int64(7)

In [34]:
# [1,2,3,4,5]
a_3 = [1,2,100, 45, 450, 2, 5]
np.argmax(a_3) # index of the max element # not aggresation function

np.int64(4)

In [35]:
np.argmin(a_3)

np.int64(0)

In [36]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220], # state-2-price,
    [34, 12, 1100, 11, 220]
])

In [37]:
np.sum(price_amazon)

np.int64(4004)

In [ ]:
np.sum(price_amazon, axis=0)
# axis->0 means sum over rows, keep columns
#|
#|
#| downward of given matrix

array([  98,   34, 3200,   32,  640])

In [ ]:
np.sum(price_amazon, axis=1) ## direction -> +->+->
# axis->1 means sum over columns, keep rows

array([1250, 1377, 1377])

In [40]:
np.mean(a_3)

np.float64(86.42857142857143)

In [41]:
np.mean(price_amazon)

np.float64(266.93333333333334)

In [42]:
np.mean(price_amazon, axis=1)

array([250. , 275.4, 275.4])

In [43]:
np.mean(price_amazon, axis=1)

array([250. , 275.4, 275.4])

In [44]:
np.var(price_amazon, axis=1)

array([145720.  , 176119.04, 176119.04])

In [48]:
np.cumsum([1,2,4,5,6,100])

array([  1,   3,   7,  12,  18, 118])

In [46]:
np.median(price_amazon, axis=1)

array([30., 34., 34.])

In [49]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50))

5.0


# sort, search, counting functions

In [50]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

In [51]:
len(arr)

10

In [52]:
print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
# Instead of returning the sorted values themselves, 
# it returns an array of indices that, when used to index the o

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]


In [56]:
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr)) # MIN - 0 , maX - 8

# 0,1,2,3,4,5,6,7,8
# 0,4,1....

Insert 4 position: 6
Unique elements: [1 2 3 5 6 8]
Count of each element: [0 4 1 1 0 1 2 0 1]


In [57]:
np.sort(arr)

array([1, 1, 1, 1, 2, 3, 5, 6, 6, 8])

In [58]:
arr_new = np.array([3, 6, 1, 1, 1, 1, 1.2, 8, 2, 5, 6])

In [ ]:
arr_new  #if 1 element is float, then entire array will be float type

array([3. , 6. , 1. , 1. , 1. , 1. , 1.2, 8. , 2. , 5. , 6. ])

In [60]:
print("Count of each element:", np.bincount(arr_new))

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [61]:
arr = np.array([1, 2, 3, 4])
for x in arr:
    print(x)

1
2
3
4


In [62]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [63]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np.arange(11) # can we reshape this using arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(8)
#2,4
#1,8
#2,2,2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr = np.arange(8).reshape(2,2,2) #(2,2,2) means 2 of 2,2

In [72]:
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
arr.ndim # ndim is a attibute of the class

3

In [68]:
for i in arr:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
# "nditer()"" is function to iterate to inner level of array
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [75]:
a=np.array([1,2,3])

In [76]:
b=a #b is refering value of a


In [77]:
print(id(a))
print(id(b))

2267061440880
2267061440880


In [78]:
b[0]=100

In [79]:
print(a)

[100   2   3]


In [80]:
#a.copy() # this will create same data of a , but create new memory location
b=a.copy()

In [81]:
print(id(a))
print(id(b))

2267061440880
2267037512496


In [82]:
a = np.array([1, 2, 3,])

b = a.view()

In [83]:
print(id(a))
print(id(b))

2267037513744
2267061440880


In [84]:
print(np.shares_memory(a, b))

True


In [ ]:
# vstack - vertical stack - in computer vision

a = np.array([[1,2]])
b = np.array([[3,4]])

In [86]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [ ]:
print(np.hstack((a,b))) #the inner values will merge kind of append

[[1 2 3 4]]


# numpy char and strings

In [ ]:
#np.char.<function_name>()

In [88]:
# 1. np.add()

# "hello" + "hello"

a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [89]:
#np.char.multiply()
print(np.char.multiply(a,2))

['hellohello' 'worldworld']


In [94]:
a = np.array(["=====","====="])
print(np.char.multiply(a,5))

['=========================' '=========================']


In [95]:
# np.char.upper() / lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [96]:
# np.char.center()

print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***WORLD***']


In [97]:
def password(value):
    # print(value[-4:])
    p = np.array([value[-4:]])
    print(p)
    print(np.char.center(p, 30, fillchar='*'))

In [98]:
password('mahesh puppala')

['pala']
['*************pala*************']


In [99]:
# np.char.replace()
a = np.array(['data_science', 'machine_learning'])

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [100]:
# np.char.split()

print(np.char.split(a, sep='_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [101]:
# np.char.find() / np.char.count()
print(np.char.find(a, 'learn')) 
# ['data_science', 'machine_learning']

[-1  8]


In [102]:
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))

[2 2]
[1 0]


# NUMPY COMPLETED